# Generated by Django 6.1.1 on 2026-09-26 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='danilooliv.m@hotmail.com', max_length=254, verbose_name='e-mail de atendimento')),
                ('whatsapp', models.CharField(blank=True, help_text='Somente números, incluindo país e DDD. Deixe vazio enquanto o número não estiver definido.', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', 'Use somente números, incluindo país e DDD.')], verbose_name='número do WhatsApp Business')),
                ('whatsapp_ativo', models.BooleanField(default=False, verbose_name='exibir WhatsApp no site')),
            ],
            options={
                'verbose_name': 'configuração de contato',
                'verbose_name_plural': 'configuração de contato',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='contato_registro_unico')],
            },
        ),
    ]
