# Generated by Django 6.1.1 on 2026-09-27 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acesso_pendente',
            field=models.BooleanField(default=False, editable=False, verbose_name='aguardando definição da senha'),
        ),
        migrations.AddField(
            model_name='user',
            name='versao_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
