"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-r0_+^exuo8+kr=lzz6t3_t0b4m(27a271yq%#v%e&2@e7)40u!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps do projeto
    "accounts",
    "comunicacao.apps.ComunicacaoConfig",
    "core",
    "portfolio",
    "clientes",
    "painel",
    "area_cliente.apps.AreaClienteConfig",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.canais_contato",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# E-mail: modo console por padrão. Credenciais somente no ambiente.
SITE_URL = os.environ.get("SITE_URL", "http://127.0.0.1:8000").rstrip("/")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "nao-responda@example.com")
EMAIL_REPLY_TO = os.environ.get("EMAIL_REPLY_TO", "")
EMAIL_EQUIPE = os.environ.get("EMAIL_EQUIPE", "")
SMTP_HOST = os.environ.get("EMAIL_HOST", "")
SMTP_PORT = int(os.environ.get("EMAIL_PORT", "587"))
SMTP_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
SMTP_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() == "true"
EMAIL_ENVIO_IMEDIATO = os.environ.get("EMAIL_ENVIO_IMEDIATO", "true").lower() == "true"
EMAIL_NOTIFICACOES_ATIVAS = os.environ.get("EMAIL_NOTIFICACOES_ATIVAS", "true").lower() == "true"
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24
MAILERS = {"default": {"BACKEND": os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")}}
if MAILERS["default"]["BACKEND"] == "django.core.mail.backends.smtp.EmailBackend":
    MAILERS["default"]["OPTIONS"] = {
        "host": SMTP_HOST, "port": SMTP_PORT,
        "username": os.environ.get("EMAIL_HOST_USER", ""),
        "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
        "use_tls": SMTP_USE_TLS, "use_ssl": SMTP_USE_SSL, "timeout": 10,
    }

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Nunca servir esta pasta como mídia ou conteúdo estático.
PRIVATE_FILES_ROOT = BASE_DIR / "private_uploads"
