# Generated by Django 6.1.1 on 2026-09-26 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('slug', models.SlugField(help_text='Ex.: atlas-semi-joias. Evite alterar depois de divulgar o link.', max_length=160, unique=True, verbose_name='endereço da página')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('resumo', models.CharField(max_length=280, verbose_name='resumo')),
                ('descricao', models.TextField(verbose_name='apresentação do projeto')),
                ('desafio', models.TextField(blank=True, verbose_name='o desafio')),
                ('solucao', models.TextField(blank=True, verbose_name='minha contribuição')),
                ('aprendizados', models.TextField(blank=True, verbose_name='aprendizados e próximos passos')),
                ('status', models.CharField(choices=[('desenvolvimento', 'Em desenvolvimento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='desenvolvimento', max_length=20, verbose_name='status')),
                ('capa', models.ImageField(blank=True, help_text='Opcional. JPG, PNG ou WebP; prefira uma imagem horizontal.', upload_to='projetos/capas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagem de capa')),
                ('capa_alt', models.CharField(blank=True, max_length=180, verbose_name='descrição da imagem')),
                ('capa_estilo', models.CharField(choices=[('padrao', 'Azul e cinza'), ('atlas', 'Atlas Semi-Joias')], default='padrao', max_length=12, verbose_name='capa sem imagem')),
                ('link_site', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='link do projeto')),
                ('link_repositorio', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='link do repositório')),
                ('publicado', models.BooleanField(default=False, help_text='Exibe o projeto na listagem e libera sua página individual.', verbose_name='publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Dentro do mesmo grupo, números menores aparecem primeiro.', verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ('-destaque', 'ordem', '-criado_em', 'pk'),
            },
        ),
    ]
