# Generated by Django 6.1.1 on 2026-09-27 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_solicitacao_tipo_ordemmanutencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso', 'Convite de acesso'), ('senha', 'Recuperação de senha'), ('atualizacao', 'Atualização do atendimento'), ('mensagem', 'Nova mensagem'), ('arquivo', 'Novo arquivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendente', 'Aguardando envio'), ('enviando', 'Em envio'), ('enviado', 'Aceito pelo servidor de e-mail'), ('simulado', 'Simulado — sem envio real'), ('falha', 'Falha no envio'), ('cancelado', 'Envio cancelado')], db_index=True, default='pendente', max_length=12)),
                ('destinatario', models.EmailField(max_length=254)),
                ('para_equipe', models.BooleanField(default=False)),
                ('referencia_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chave', models.CharField(max_length=120, unique=True)),
                ('versao_acesso', models.UUIDField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('resultado', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_email', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.solicitacao')),
            ],
            options={
                'verbose_name': 'entrega de e-mail',
                'verbose_name_plural': 'entregas de e-mail',
                'ordering': ('-criado_em', '-pk'),
            },
        ),
    ]
