# Generated by Django 6.1.1 on 2026-09-26 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('tipo', models.CharField(choices=[('projeto', 'Projeto'), ('servico', 'Serviço')], default='projeto', max_length=10, verbose_name='tipo')),
                ('descricao', models.TextField(verbose_name='escopo contratado')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('planejamento', 'Em planejamento'), ('andamento', 'Em andamento'), ('aguardando_cliente', 'Aguardando você'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='recebida', max_length=20, verbose_name='status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, help_text='Percentual informado por você. Ao concluir pelo admin, será ajustado para 100%.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='progresso (%)')),
                ('proximo_passo', models.TextField(blank=True, help_text='Explique a próxima entrega ou o que precisa receber do cliente.', verbose_name='próximo passo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='previsão de entrega')),
                ('visivel_cliente', models.BooleanField(default=False, help_text='Marque para liberar a contratação e seu histórico no painel do cliente.', verbose_name='visível para o cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'projeto ou serviço contratado',
                'verbose_name_plural': 'projetos e serviços contratados',
                'ordering': ('-atualizado_em', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='AtualizacaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('visivel_cliente', models.BooleanField(default=True, verbose_name='visível para o cliente')),
                ('status_registrado', models.CharField(blank=True, choices=[('recebida', 'Recebida'), ('planejamento', 'Em planejamento'), ('andamento', 'Em andamento'), ('aguardando_cliente', 'Aguardando você'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='status no registro')),
                ('progresso_registrado', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='progresso no registro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('autor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='clientes.solicitacao', verbose_name='contratação')),
            ],
            options={
                'verbose_name': 'atualização da contratação',
                'verbose_name_plural': 'atualizações das contratações',
                'ordering': ('-criado_em', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['cliente', 'visivel_cliente', 'status'], name='sol_cliente_vis_status'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='sol_progresso_0_100'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'concluida'), _negated=True), ('progresso', 100), _connector='OR'), name='sol_concluida_100'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('prazo__isnull', True), ('data_inicio__isnull', True), ('prazo__gte', models.F('data_inicio')), _connector='OR'), name='sol_prazo_apos_inicio'),
        ),
    ]
