# Generated by Django 6.1.1 on 2026-09-26 18:26

import clientes.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título do arquivo')),
                ('arquivo', models.FileField(max_length=255, storage=clientes.storage.private_storage, upload_to=clientes.storage.caminho_arquivo, validators=[clientes.storage.validar_arquivo], verbose_name='arquivo')),
                ('nome_original', models.CharField(editable=False, max_length=255, verbose_name='nome original')),
                ('tamanho', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='tamanho em bytes')),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('equipe', 'Atendimento')], default='equipe', editable=False, max_length=10, verbose_name='enviado por')),
                ('visivel_cliente', models.BooleanField(default=True, verbose_name='visível para o cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('enviado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='clientes.solicitacao', verbose_name='contratação')),
            ],
            options={
                'verbose_name': 'arquivo da contratação',
                'verbose_name_plural': 'arquivos das contratações',
                'ordering': ('-criado_em', '-pk'),
            },
        ),
    ]
