# Generated by Django 6.1.1 on 2026-09-26 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_arquivosolicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('equipe', 'Atendimento')], default='equipe', editable=False, max_length=10, verbose_name='enviada por')),
                ('texto', models.TextField(max_length=5000, verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('lida_cliente_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='lida pelo cliente em')),
                ('lida_equipe_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='lida pela equipe em')),
                ('autor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='clientes.solicitacao', verbose_name='contratação')),
            ],
            options={
                'verbose_name': 'mensagem da contratação',
                'verbose_name_plural': 'mensagens das contratações',
                'ordering': ('-criado_em', '-pk'),
                'indexes': [models.Index(fields=['solicitacao', 'origem', 'lida_cliente_em'], name='msg_cliente_leitura'), models.Index(fields=['origem', 'lida_equipe_em'], name='msg_equipe_leitura')],
            },
        ),
    ]
