# Generated by Django 6.1.1 on 2026-09-26 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_mensagemsolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('projeto', 'Projeto'), ('servico', 'Serviço'), ('manutencao', 'Manutenção técnica')], default='projeto', max_length=10, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('solicitacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.solicitacao')),
                ('equipamento', models.CharField(choices=[('computador', 'Computador'), ('notebook', 'Notebook')], max_length=12, verbose_name='equipamento')),
                ('marca', models.CharField(max_length=80, verbose_name='marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=120, verbose_name='número de série')),
                ('relato_cliente', models.TextField(verbose_name='problema relatado pelo cliente')),
                ('acessorios', models.TextField(blank=True, verbose_name='acessórios recebidos')),
                ('condicao_recebimento', models.TextField(blank=True, verbose_name='condição do equipamento no recebimento')),
                ('diagnostico_publico', models.TextField(blank=True, verbose_name='diagnóstico visível ao cliente')),
                ('servico_realizado', models.TextField(blank=True, verbose_name='serviço realizado / orientação ao cliente')),
                ('anotacoes_internas', models.TextField(blank=True, help_text='Somente na administração. Não registre senhas de acesso do equipamento.', verbose_name='anotações técnicas internas')),
                ('etapa', models.CharField(choices=[('agendado', 'Recebimento agendado'), ('recebido', 'Equipamento recebido'), ('diagnostico', 'Em diagnóstico'), ('orcamento', 'Orçamento em negociação'), ('aguardando_peca', 'Aguardando peça'), ('manutencao', 'Em manutenção'), ('testes', 'Em testes'), ('pronto', 'Pronto para entrega ou retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='etapa da manutenção')),
                ('orcamento_acordado', models.BooleanField(default=False, help_text='Marque somente após combinar os valores pelo contato. O cliente consultará o registro, sem aprovar pelo site.', verbose_name='orçamento já acordado com o cliente')),
                ('detalhes_orcamento', models.TextField(blank=True, verbose_name='descrição do que foi acordado')),
                ('valor_servicos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='serviços (R$)')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peças (R$)')),
                ('valor_logistica', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coleta e entrega (R$)')),
                ('data_acordo', models.DateField(blank=True, null=True, verbose_name='data do acordo')),
                ('pagamento_combinado', models.CharField(blank=True, max_length=200, verbose_name='condição de pagamento combinada')),
                ('recebimento', models.CharField(choices=[('coleta', 'Coleta por Danilo'), ('cliente', 'Entrega pelo cliente')], default='coleta', max_length=10, verbose_name='forma de recebimento')),
                ('coleta_prevista', models.DateTimeField(blank=True, null=True, verbose_name='recebimento / coleta agendada')),
                ('recebido_em', models.DateField(blank=True, null=True, verbose_name='recebido em')),
                ('devolucao', models.CharField(choices=[('entrega', 'Entrega por Danilo'), ('retirada', 'Retirada pelo cliente')], default='entrega', max_length=10, verbose_name='forma de devolução')),
                ('devolucao_prevista', models.DateTimeField(blank=True, null=True, verbose_name='entrega / retirada agendada')),
                ('entregue_em', models.DateField(blank=True, null=True, verbose_name='entregue em')),
                ('endereco_atendimento', models.TextField(blank=True, help_text='Visível somente nesta ordem, ao cliente titular e à administração.', verbose_name='endereço combinado para coleta / entrega')),
                ('observacoes_logistica', models.TextField(blank=True, verbose_name='orientações de coleta / entrega')),
            ],
            options={
                'verbose_name': 'ordem de manutenção técnica',
                'verbose_name_plural': 'manutenção técnica — ordens de serviço',
                'ordering': ('-atualizado_em', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_servicos__isnull', True), ('valor_servicos__gte', 0), _connector='OR'), name='os_servicos_positivo'), models.CheckConstraint(condition=models.Q(('valor_pecas__gte', 0), ('valor_logistica__gte', 0)), name='os_custos_positivos'), models.CheckConstraint(condition=models.Q(models.Q(('orcamento_acordado', True), _negated=True), models.Q(('valor_servicos__isnull', False), ('data_acordo__isnull', False)), _connector='OR'), name='os_acordo_com_valor_data'), models.CheckConstraint(condition=models.Q(('entregue_em__isnull', True), ('recebido_em__isnull', True), ('entregue_em__gte', models.F('recebido_em')), _connector='OR'), name='os_entrega_apos_recebimento')],
            },
            bases=('clientes.solicitacao',),
        ),
    ]
